### ISSUE TITLE
Improve extractor options

### ISSUE THREAD

**Issue by xypwn** [xypwn/filediver#79]
Currently, the extractor options can be very hard to follow at times. This is mainly because the options system is designed quite poorly. Some examples (in no particular order, numbers for reference only):
1. Many options only apply if certain other options (e.g. image_format, format etc.) have a specific value.
2. Many options are duplicated between different formats.
3. Some options aren't duplicated and instead depend on other formats' options, but that dependency isn't communicated.
4. It's not communicated that "raw" applies to anything not extractable OR anything where "source" is the selected format.
5. "blend" format is displayed as available even if the blender exporter isn't available. This doesn't communicate to the user why exporting blend actually exports to GLB and could be very frustrating.
6. A few formats have MANY different options, most of which the average user doesn't need to touch.

NOTE: I just came up with all of these ideas on a whim and they're still very preliminary. I also likely won't have much time to work on Filediver in the very near future (2025-06-08).

**Comment by xypwn** [comment]
Some ideas:
- 1.:
  - Allow declaring dependencies on other options having specific values.
- 5.:
  - Add the ability to dynamically declare some option "unavailable" with the inclusion of a region (e.g. "blender importer not found").
- 6.:
  - Add an "advanced" boolean to each option. "advanced" options are only shown if the user checks a box in the GUI or passes a flag to the CLI help.

**To really mitigate these issues in the long term, though, a more radical redesign is probably needed**. Here are some ideas:
No longer pass settings on a per-extractor basis, but instead create a large ExtractorOptions struct, which every extractor can fully access. With that, we can instead of e.g. "wwise_stream" or "wwise_bank" simply say "audio.format"; or "mesh.include_lods", "animation.sample_rate" etc., also including a more human-readable name and description. This could fully solve 2, 3 and 4. It would also drastically improve the GUI experience.

**Comment by xypwn** [comment]
@ryanjsims I thought you might be interested in this, since you have been doing a lot of extractor work and I feel like you might have had to deal with my poor design decisions regarding the extractor options a decent bit. In my experience, extractor options have also been one of the things users have been struggling with the most.
I haven't tagged you on more high-level topics like this before, so let me know in case you're not interested (which is perfectly fine :)) and I won't tag you.

**Comment by ryanjsims** [comment]
I think having something where the full configuration is passed to every extractor would be a good step towards solving some of the issues

Also it would be nice to have some way of including documentation about a setting with the setting itself, so when I'm adding something like the animation sample rate, it can be documented right there that it only affects the sampled animation format

Finally being able to specify dependencies would be nice, maybe something where options depending on a specific format are listed underneath that format? So like:
```
animation:
    format:
        json:
            Summary: Dump the animation file to json
        source:
            Summary: Treats animation files as "raw" files
            Depends: 
                - raw.format
        sampled:
            Summary: When exporting models, animations will be sampled at "animation.sample_rate" keyframes per second
            Depends:
                - unit.enable_animations = true
                - animation.sample_rate
            Advanced: true
    sample_rate:
        Range: 12 to 120
        Summary: Sets the keyframe sample rate for animation.format = sampled
        Depends:
            - animation.format = sampled
unit:
    ...
    enable_animations:
        Summary: When enabled, models with animations will have them exported
        Depends:
            - animation.format
```
Or maybe "links" would be a better name for it?
